server:
  port: 9001
spring:
  application:
    name: canbro-coffee-dapp
  datasource:
    username: root
    password: 1111
    url: jdbc:mysql://localhost:3304/cb_coffee
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6370
